%Watermarking
clc;
close all;
[file_name,fileinfo]=uigetfile({'*.bmp;*.jpg;*.png;*.tiff;';'*.*'},'Select an Image File');
x=double(imread(fullfile(fileinfo,file_name)));
figure;
imshow(x/255);
title('Original Image');
[row,col,colour]=size(x);
y=x;
a=zeros(row,col);
row1=input('Enter the row from which you want to start watermark(min 1): ');
fprintf('Enter the row from which you want to end watermark(max %d): ',row);
row2=input('');
col1=input('Enter the column from which you want to start watermark (min 1): ');
fprintf('Enter the column from which you want to end watermark (max %d): ',col);
col2=input('');
a(row1:row2,col1:col2)=1;
x1=x(:,:,1);
x2=x(:,:,2);
x3=x(:,:,3);
dx1=dct2(x1);
dx2=dct2(x2);
dx3=dct2(x3);
g=input('How much % watermarking you want: ');
g=g*1000;
dx1(1:row,1:col)=dx1(1:row,1:col)+g*a;
dx2(1:row,1:col)=dx2(1:row,1:col)+g*a;
dx3(1:row,1:col)=dx3(1:row,1:col)+g*a;
y1=idct2(dx1);
y2=idct2(dx2);
y3=idct2(dx3);
y(:,:,1)=y1;
y(:,:,2)=y2;
y(:,:,3)=y3;
figure;
imshow(y/255);
title('Watermarked Image');
imwrite((y/255), [fileinfo 'Watermarked Image.jpg']);